[build]
builder = "NIXPACKS"
buildCommand = "pip install poetry && poetry install"

[deploy]
startCommand = "poetry run uvicorn src.main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/docs"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10